### ISSUE TITLE
about age

### ISSUE THREAD

**Issue by Gaotian-cpu** [HasnainRaz/Fast-AgingGAN#7]
Hello, I'm working on your project. I have a simple test and found that the output is not different from the original image. Is there any way to make the results older?

**Comment by HasnainRaz** [comment]
Hey,

The GAN was trained with faces at a resolution of 256x256. So if you are not seeing aging, try resizing the image so that the face is roughly 256x256, the transformation should be more apparant then.

This is something I might look into in the future to deal with, how to do face aging in the wild.
Hope this helps.
